#!/usr/bin/env bash

set -e

echo "Populating new modular directory structure in $(pwd)..."

# Array of target files to create
FILES=(
  "package.json"
  "drizzle.config.ts"
  "next.config.ts"
  "tsconfig.json"
  "public/favicon.ico"

  # Standalone Feature Modules
  "packages/feature-avatar/package.json"
  "packages/feature-avatar/tsconfig.json"
  "packages/feature-avatar/src/index.ts"
  "packages/feature-avatar/src/assets/base/base_1.svg"
  "packages/feature-avatar/src/assets/eyes/eyes_1.svg"
  "packages/feature-avatar/src/assets/eyes/eyes_2.svg"
  "packages/feature-avatar/src/assets/hair/hair_1.svg"
  "packages/feature-avatar/src/assets/hair/hair_2.svg"
  "packages/feature-avatar/src/assets/mouth/mouth_1.svg"
  "packages/feature-avatar/src/assets/mouth/mouth_2.svg"
  "packages/feature-avatar/src/components/avatar-builder.tsx"
  "packages/feature-avatar/src/components/avatar-renderer.tsx"
  "packages/feature-avatar/src/contracts/auth.ts"
  "packages/feature-avatar/src/lib/actions.ts"
  "packages/feature-avatar/src/lib/options.ts"
  "packages/feature-avatar/src/lib/types.ts"
  "packages/feature-avatar/src/lib/validation.ts"
  "packages/feature-avatar/src/schema/avatar.schema.ts"

  "packages/feature-chatbox/package.json"
  "packages/feature-chatbox/tsconfig.json"
  "packages/feature-chatbox/src/index.ts"
  "packages/feature-chatbox/src/components/chatbox-dropdown.tsx"
  "packages/feature-chatbox/src/components/chatbox-input.tsx"
  "packages/feature-chatbox/src/components/chatbox-message.tsx"
  "packages/feature-chatbox/src/components/chatbox-panel.tsx"
  "packages/feature-chatbox/src/contracts/auth.ts"
  "packages/feature-chatbox/src/lib/actions.ts"
  "packages/feature-chatbox/src/lib/queries.ts"
  "packages/feature-chatbox/src/schema/chatbox.schema.ts"
  "packages/feature-chatbox/src/styles/chatbox.module.css"

  "packages/feature-forum/package.json"
  "packages/feature-forum/tsconfig.json"
  "packages/feature-forum/src/index.ts"
  "packages/feature-forum/src/components/board-display.tsx"
  "packages/feature-forum/src/components/create-post-panel.tsx"
  "packages/feature-forum/src/components/create-reply-panel.tsx"
  "packages/feature-forum/src/components/forum-stats-panel.tsx"
  "packages/feature-forum/src/components/post-content-area.tsx"
  "packages/feature-forum/src/components/admin/admin-forum-controls.tsx"
  "packages/feature-forum/src/components/admin/admin-thread-controls.tsx"
  "packages/feature-forum/src/components/admin/create-board-panel.tsx"
  "packages/feature-forum/src/components/admin/create-category-panel.tsx"
  "packages/feature-forum/src/components/admin/edit-board-panel.tsx"
  "packages/feature-forum/src/components/admin/edit-category-panel.tsx"
  "packages/feature-forum/src/components/admin/thread-admin-button.tsx"
  "packages/feature-forum/src/components/admin/unassigned-boards.tsx"
  "packages/feature-forum/src/components/admin/view-category-content.tsx"
  "packages/feature-forum/src/components/admin/view-forum-panel.tsx"
  "packages/feature-forum/src/contracts/auth.ts"
  "packages/feature-forum/src/lib/actions.ts"
  "packages/feature-forum/src/lib/queries.ts"
  "packages/feature-forum/src/schema/forum.schema.ts"
  "packages/feature-forum/src/styles/admin.module.css"
  "packages/feature-forum/src/styles/forum.module.css"

  # Host Adapters
  "src/adapters/host-auth-adapter.ts"
  "src/adapters/host-notification-adapter.ts"

  # App Router Routes
  "src/app/favicon.ico"
  "src/app/globals.css"
  "src/app/layout.tsx"
  "src/app/page.tsx"
  "src/app/admin/page.tsx"
  "src/app/admin/audit-log/page.tsx"
  "src/app/admin/forum/page.tsx"
  "src/app/admin/forum/[catId]/page.tsx"
  "src/app/admin/forum/[catId]/[boardId]/page.tsx"
  "src/app/admin/reports/page.tsx"
  "src/app/admin/users/page.tsx"
  "src/app/admin/users/[userId]/page.tsx"
  "src/app/admin/users/[userId]/edit/page.tsx"
  "src/app/api/auth/[...all]/route.ts"
  "src/app/avatar/page.tsx"
  "src/app/components/theme-provider.tsx"
  "src/app/components/theme-toggle.tsx"
  "src/app/dashboard/page.tsx"
  "src/app/forum/page.tsx"
  "src/app/forum/[catId]/page.tsx"
  "src/app/forum/[catId]/[boardId]/page.tsx"
  "src/app/forum/[catId]/[boardId]/thread/[threadId]/page.tsx"
  "src/app/home/page.tsx"
  "src/app/login/page.tsx"
  "src/app/notifications/page.tsx"
  "src/app/register/page.tsx"
  "src/app/settings/page.tsx"
  "src/app/test/chatbox/page.tsx"
  "src/app/test/styles/page.tsx"
  "src/app/test/styles/style-test.css"
  "src/app/user/[userId]/page.tsx"

  # Core System & Governance
  "src/core/index.ts"
  "src/core/admin/index.ts"
  "src/core/admin/components/admin-edit-user-form.tsx"
  "src/core/admin/components/admin-forum-management-panel.tsx"
  "src/core/admin/components/admin-posting-status-form.tsx"
  "src/core/admin/components/admin-user-table.tsx"
  "src/core/admin/components/delete-user-modal.tsx"
  "src/core/admin/lib/actions.ts"
  "src/core/admin/lib/forum-actions.ts"
  "src/core/auth/index.ts"
  "src/core/auth/components/auth-card.tsx"
  "src/core/auth/components/sign-out-button.tsx"
  "src/core/auth/lib/auth.ts"
  "src/core/auth/lib/auth-client.ts"
  "src/core/auth/lib/require-session.ts"
  "src/core/auth/lib/require-user.ts"
  "src/core/auth/routes/auth-route-handler.ts"
  "src/core/auth/schema/auth.schema.ts"
  "src/core/dashboard/components/app-shell.tsx"
  "src/core/dashboard/components/app-shell-frame.tsx"
  "src/core/dashboard/components/breadcrumbs.tsx"
  "src/core/dashboard/components/header.tsx"
  "src/core/dashboard/components/sidebar.tsx"
  "src/core/dashboard/components/sidebar-frame.tsx"
  "src/core/dashboard/components/sidebar-toggle-button.tsx"
  "src/core/dashboard/components/panels/main-card.tsx"
  "src/core/dashboard/components/panels/page-header.tsx"
  "src/core/registry/modules.config.ts"
  "src/core/settings/index.ts"
  "src/core/settings/components/account-settings-form.tsx"

  # Shared Libraries & Primitives
  "src/shared/communication/author/lib/author.ts"
  "src/shared/communication/interactions/lib/actions.ts"
  "src/shared/communication/interactions/schema/interactions.schema.ts"
  "src/shared/communication/mentions/lib/mentions.ts"
  "src/shared/communication/mentions/schema/mentions.schema.ts"
  "src/shared/communication/moderation/lib/audit-log.ts"
  "src/shared/communication/moderation/schema/moderation.schema.ts"
  "src/shared/communication/notifications/components/notification-dropdown.tsx"
  "src/shared/communication/notifications/components/notification-panel.tsx"
  "src/shared/communication/notifications/lib/actions.ts"
  "src/shared/communication/notifications/lib/notify.ts"
  "src/shared/communication/notifications/lib/queries.ts"
  "src/shared/communication/notifications/schema/notifications.schema.ts"
  "src/shared/communication/permissions/lib/permissions.ts"
  "src/shared/communication/permissions/schema/permissions.schema.ts"
  "src/shared/communication/sanitize/lib/sanitize.ts"
  "src/shared/communication/social/lib/can-interact.ts"
  "src/shared/communication/social/schema/blocks.schema.ts"
  "src/shared/communication/status/lib/status.ts"
  "src/shared/communication/status/lib/trust.ts"
  "src/shared/communication/status/schema/status.schema.ts"
  "src/shared/components/breadcrumb-label.tsx"
  "src/shared/components/breadcrumbs-context.tsx"
  "src/shared/components/dropdown-menu.tsx"
  "src/shared/components/expandable-menu-item.tsx"
  "src/shared/components/lorem-ipsum.tsx"
  "src/shared/components/placeholder.tsx"
  "src/shared/components/report-panel.tsx"
  "src/shared/db/client.ts"
  "src/shared/db/schema.ts"
  "src/shared/db/seed/migrate-debug.ts"
  "src/shared/db/seed/run-seed.ts"
  "src/shared/db/seed/seed-config.ts"
  "src/shared/db/seed/seed-roles.ts"
  "src/shared/db/seed/seed-users.ts"
  "src/shared/styles/brand.module.css"
  "src/shared/styles/buttons.module.css"
  "src/shared/styles/form.module.css"
  "src/shared/styles/modal.module.css"
  "src/shared/styles/panel.module.css"
  "src/shared/styles/tables.module.css"
  "src/shared/styles/patterns/breadcrumbs.module.css"
  "src/shared/styles/patterns/card.module.css"
  "src/shared/styles/patterns/dropdown-menu.module.css"
  "src/shared/styles/patterns/sidebar.module.css"
  "src/shared/styles/patterns/table-of-contents.module.css"
  "src/shared/styles/patterns/tabs.module.css"
  "src/shared/svg/bell-icon.svg"
  "src/shared/svg/bootstrap-bell-icon.svg"
  "src/shared/svg/bootstrap-chat-icon.svg"
  "src/shared/svg/bootstrap-close-icon.svg"
  "src/shared/svg/bootstrap-css-icon.svg"
  "src/shared/svg/bootstrap-down-arrow-icon.svg"
  "src/shared/svg/bootstrap-edit-icon.svg"
  "src/shared/svg/bootstrap-exit-icon.svg"
  "src/shared/svg/bootstrap-forum-icon.svg"
  "src/shared/svg/bootstrap-gear-icon.svg"
  "src/shared/svg/bootstrap-heart-icon.svg"
  "src/shared/svg/bootstrap-left-square-icon.svg"
  "src/shared/svg/bootstrap-like-icon.svg"
  "src/shared/svg/bootstrap-person-icon.svg"
  "src/shared/svg/bootstrap-question-icon.svg"
  "src/shared/svg/bootstrap-right-square-icon.svg"
  "src/shared/svg/bootstrap-search-icon.svg"
  "src/shared/svg/bootstrap-settings.svg"
  "src/shared/svg/bootstrap-three-dot-icon.svg"
  "src/shared/svg/bootstrap-trash-icon.svg"
  "src/shared/svg/card-icon.svg"
  "src/shared/svg/four-squares-icon.svg"
  "src/shared/svg/gear-icon.svg"
  "src/shared/svg/graph-icon.svg"
  "src/shared/svg/left-arrow.svg"
  "src/shared/svg/page-icon.svg"
  "src/shared/svg/team-icon.svg"
)

for file in "${FILES[@]}"; do
  dir=$(dirname "$file")
  mkdir -p "$dir"
  if [ ! -f "$file" ]; then
    touch "$file"
  fi
done

echo "Successfully populated target structure with ${#FILES[@]} files!"
```
